version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
    ports:
      - '3305:3306'
    expose:
      - '3305'
    volumes:
      - ./mysql_data:/var/lib/mysql

  apache:
    image: httpd:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./apache_web:/usr/local/apache2/htdocs
      - ./apache_conf:/etc/apache2/sites-available


